### ISSUE TITLE
建议abstract字段拆解

### ISSUE THREAD

**Issue by izturn** [qiaohaoforever/DoubanBook#10]
首先谢谢分享, 另外目前的abastract字段包含的内容不定,解析困难,建议拆解成"作者"，"价格"等更细致的字段

**Comment by qiaohaoforever** [comment]
下一版本已用具体字段取代abstract，正考虑哪种方案更合适。

**Comment by izturn** [comment]
nice, 能请问一下用abstract的优势在哪儿么？

**Comment by qiaohaoforever** [comment]
原因在于现有数据的abstract无法完全抽取具体字段，向前兼容的问题

**Comment by qiaohaoforever** [comment]
目前新的数据是按照book_info的方案存储的，老数据没有更新替换。
![](https://pic.downk.cc/item/5f3f8fae160a154a67b582a9.png)

**Comment by izturn** [comment]
nice,thx
