### ISSUE TITLE
用公开key调用api，始终返回429，Too many request

### ISSUE THREAD

**Issue by eagle-lk** [qiaohaoforever/DoubanBook#27]
"https://api.feelyou.top/isbn/", public key是从公众号申请的，请问接口还能用吗？

**Comment by qiaohaoforever** [comment]
接口还能用，个人key的使用正常有效，公共key有人在高频爬取，触发频次限制🚫目前正在研究如何对付。

**Comment by eagle-lk** [comment]
明白了。昨天有一段时间是可用的。谢谢提供服务。
