### ISSUE TITLE
根据分类查看书籍列表

### ISSUE THREAD

**Issue by zairl23** [qiaohaoforever/DoubanBook#6]
最近准备开发一个关于阅读的小程序，首页会有根据分类来查看书籍的交互。是否会增加一个根据分类查看书籍列表呢？

**Comment by qiaohaoforever** [comment]
目前暂时还没有分类列表的计划，分类标签现在太杂不好定义。您可以描述一下您的计划，大致的定义方案。

**Comment by zairl23** [comment]
是的，有些复制，所以现在也决定先不做分类。

**Comment by qiaohaoforever** [comment]
小程序上线了吗？分享出来体验体验～

**Comment by zairl23** [comment]
还没有发布，开发中，到时分享一下。



---原始邮件---
发件人: "正版乔"<notifications@github.com&gt;
发送时间: 2020年5月6日(周三) 晚上6:24
收件人: "qiaohaoforever/DoubanBook"<DoubanBook@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ney chang"<3082784291@qq.com&gt;;
主题: Re: [qiaohaoforever/DoubanBook] 根据分类查看书籍列表 (#6)




 
小程序上线了吗？分享出来体验体验～
