### ISSUE TITLE
图书名称查询失效

### ISSUE THREAD

**Issue by hornhuang** [qiaohaoforever/DoubanBook#8]
图书名称查询失效

查询：https://book.feelyou.top/search/人工智能

返回：Internal Server Error

**Comment by qiaohaoforever** [comment]
有人在疯狂爬虫，太频繁了。建议换个时间再查。

**Comment by hornhuang** [comment]
疯狂爬虫。。。这老哥真的是。。。感谢博主分享这个库

**Comment by qiaohaoforever** [comment]
瞧，现在就可以了～
![](https://pic.downk.cc/item/5eb65ad5c2a9a83be5a8d873.png)

**Comment by hornhuang** [comment]
very good，我可以拿来写下一个 Demo 了
